name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run example
        run: python example.py
      - name: Save output
        run: python example.py > output-${{ matrix.python-version }}.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-${{ matrix.python-version }}
          path: output-${{ matrix.python-version }}.txt
